version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app
  server:
    container_name: bugzilla_server
    image: bugzilla_server:0.0.1
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - mongodb
    networks:
      - mern-app
  client:
    container_name: bugzilla_client
    image: bugzilla_client:0.0.1
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - server
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
